modLoader="javafml"
loaderVersion="[${fml_min},)"
license="${mod_license}"

[[mods]]
modId = "chestbubbles"
version = "${mod_version}"
displayName = "${mod_name}"
description = "${mod_description}"

[[dependencies.chestbubbles]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.chestbubbles]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="AFTER"
    side="BOTH"